Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, inline: "apt-get install dos2unix && dos2unix /vagrant/vagrant_bootstrap.sh && /vagrant/vagrant_bootstrap.sh", run: "always"
  config.vm.network "private_network", ip: "10.10.10.20"
end
